export const events = [
    {
        title: "Next.js Conf 2026",
        image: "/images/event1.png",
        slug: "nextjs-conf-2026",
        location: "San Francisco, CA",
        date: "October 25, 2026",
        time: "10:00 AM",
    },
    {
        title: "React Summit",
        image: "/images/event2.png",
        slug: "react-summit",
        location: "Amsterdam, NL",
        date: "June 14, 2026",
        time: "09:00 AM",
    },
    {
        title: "Web Dev Hackathon",
        image: "/images/event3.png",
        slug: "web-dev-hackathon",
        location: "Online",
        date: "August 20, 2026",
        time: "12:00 PM",
    },
    {
        title: "JS World Conference",
        image: "/images/event4.png",
        slug: "js-world-conference",
        location: "London, UK",
        date: "September 12, 2026",
        time: "08:30 AM",
    },
    {
        title: "AI in Tech Meetup",
        image: "/images/event5.png",
        slug: "ai-in-tech-meetup",
        location: "New York, NY",
        date: "November 05, 2026",
        time: "06:30 PM",
    },
    {
        title: "Frontend Masters Workshop",
        image: "/images/event6.png",
        slug: "frontend-masters-workshop",
        location: "Austin, TX",
        date: "December 10, 2026",
        time: "01:00 PM",
    },
];
